### ISSUE TITLE
data not available

### ISSUE THREAD

**Issue by mohammed-shabeer** [nahlik-michal/kaggle-melbourne-seizure-prediction#1]
hey there,
can i have the data of this project[kaggle-melbourne-seizure-prediction](https://github.com/michal-nahlik/kaggle-melbourne-seizure-prediction) to include in my project. in the kaggle competition site, the data was removed
thank you

**Comment by michal-nahlik** [comment]
Hello,
unfortunatelly I don't have the data anymore but the project continues here:
https://www.epilepsyecosystem.org/
after registering you should be able to get the data there.
